//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocFileBeforeAppr
    {
        public int file_id { get; set; }
        public string path_file { get; set; }
        public string issue_no { get; set; }
    
        public virtual Issue Issue { get; set; }
    }
}
