//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocFile
    {
        public int file_id { get; set; }
        public string file_name { get; set; }
        public int relation_id { get; set; }
    
        public virtual Relation_Issue_Cust Relation_Issue_Cust { get; set; }
    }
}
