//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocType
    {
        public DocType()
        {
            this.Issue = new HashSet<Issue>();
        }
    
        public int doc_type_id { get; set; }
        public string doc_type_name { get; set; }
        public int doc_parent { get; set; }
    
        public virtual ICollection<Issue> Issue { get; set; }
    }
}
