//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public Issue()
        {
            this.DocFileBeforeAppr = new HashSet<DocFileBeforeAppr>();
            this.GroupReview = new HashSet<GroupReview>();
            this.Relation_Issue_Cust = new HashSet<Relation_Issue_Cust>();
            this.Transaction = new HashSet<Transaction>();
        }
    
        public string issue_no { get; set; }
        public int doc_type_id { get; set; }
        public string doc_name { get; set; }
        public string doc_no { get; set; }
        public string doc_rev { get; set; }
        public System.DateTime rec_date { get; set; }
        public string change_point { get; set; }
        public string tnc_product { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
    
        public virtual ICollection<DocFileBeforeAppr> DocFileBeforeAppr { get; set; }
        public virtual DocType DocType { get; set; }
        public virtual ICollection<GroupReview> GroupReview { get; set; }
        public virtual ICollection<Relation_Issue_Cust> Relation_Issue_Cust { get; set; }
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
