//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation_Issue_Cust
    {
        public Relation_Issue_Cust()
        {
            this.DocFile = new HashSet<DocFile>();
        }
    
        public int id { get; set; }
        public string cust_no { get; set; }
        public string issue_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<DocFile> DocFile { get; set; }
        public virtual Issue Issue { get; set; }
    }
}
