//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RunNumberCenterEntities : DbContext
    {
        public RunNumberCenterEntities()
            : base("name=RunNumberCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TD_RunNumber> TD_RunNumber { get; set; }
        public DbSet<TM_Program> TM_Program { get; set; }
        public DbSet<TM_ResetCountPoint> TM_ResetCountPoint { get; set; }
    }
}
