//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_RunNumber
    {
        public int ProgramId { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string Additional { get; set; }
        public int RunningNumber { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual TM_Program TM_Program { get; set; }
    }
}
