//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Program
    {
        public TM_Program()
        {
            this.TD_RunNumber = new HashSet<TD_RunNumber>();
        }
    
        public int ProgramId { get; set; }
        public string ProgramName { get; set; }
        public string RunNoPattern { get; set; }
        public byte YearDigit { get; set; }
        public byte RunDigit { get; set; }
        public byte ResetCountPoint { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ICollection<TD_RunNumber> TD_RunNumber { get; set; }
        public virtual TM_ResetCountPoint TM_ResetCountPoint { get; set; }
    }
}
