//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string issue_no { get; set; }
        public string seq { get; set; }
        public string status_id { get; set; }
        public string action_id { get; set; }
        public string actor { get; set; }
        public string actor_date { get; set; }
        public string org_id { get; set; }
        public string level_id { get; set; }
        public string comment { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Status Status { get; set; }
        public virtual User_level User_level { get; set; }
    }
}
