//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_level
    {
        public User_level()
        {
            this.Transaction = new HashSet<Transaction>();
        }
    
        public string level_id { get; set; }
        public string level_name { get; set; }
        public string position_min { get; set; }
        public string position_max { get; set; }
    
        public virtual ICollection<Transaction> Transaction { get; set; }
    }
}
