//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ControlledDocument
    {
        public string issue_no { get; set; }
        public string cust_name { get; set; }
        public string doc_type_name { get; set; }
        public string doc_name { get; set; }
        public string doc_no { get; set; }
        public string doc_rev { get; set; }
        public System.DateTime rec_date { get; set; }
        public string change_point { get; set; }
        public string tnc_product { get; set; }
        public string file_name { get; set; }
        public Nullable<int> action_id { get; set; }
    }
}
