//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExDoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TransactionEmp
    {
        public string issue_no { get; set; }
        public int seq { get; set; }
        public Nullable<int> action_id { get; set; }
        public string action_name { get; set; }
        public int status_id { get; set; }
        public string status_name { get; set; }
        public Nullable<int> org_id { get; set; }
        public string org_name { get; set; }
        public string lvl_name { get; set; }
        public string comment { get; set; }
        public string remark { get; set; }
        public string comment_pic { get; set; }
        public string actor { get; set; }
        public string actor_name { get; set; }
        public string position_name { get; set; }
        public Nullable<System.DateTime> actor_date { get; set; }
    }
}
